MvcCacheRedis/Models/ErrorViewModel.cs
namespace MvcCacheRedis.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcCacheRedis/Models/Producto.cs
namespace MvcCacheRedis.Models
{
    public class Producto
    {
        public int IdProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int Precio { get; set; }
        public string Imagen { get; set; }

    }
}

MvcCacheRedis/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCacheRedis.Models;
using System.Diagnostics;

namespace MvcCacheRedis.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcCacheRedis/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCacheRedis.Models;
using MvcCacheRedis.Repositories;
using MvcCacheRedis.Services;

namespace MvcCacheRedis.Controllers
{
    public class ProductosController : Controller
    {
        private RepositoryProductos repo;
        private ServiceCacheRedis service;

        public ProductosController(RepositoryProductos repo, ServiceCacheRedis service)
        {
            this.repo = repo;
            this.service = service;
        }

        public IActionResult Index()
        {
            List<Producto> productos = this.repo.GetProductos();
            return View(productos);
        }

        public IActionResult Details(int id)
        {
            Producto producto = this.repo.FindProducto(id);
            return View(producto);
        }

        public IActionResult Favoritos()
        {
            List<Producto> favoritos = this.service.GetProductosFavoritos();
            return View(favoritos);
        }

        public IActionResult SeleccionarFavorito(int id)
        {
            //BUSCAMOS EL PRODUCTO A ALMACENAR, QUE LO TENEMOS EN EL REPOSITORY XML
            Producto producto = this.repo.FindProducto(id);
            //ALMACENAMOS EL PRODUCTO EN AZURE
            this.service.AddProductoFavorito(producto);
            ViewData["MENSAJE"] = "Producto almacenado: " + producto.Nombre;
            return RedirectToAction("Details", new { id = id });

        }

        //METODO PARA ELIMINAR UN FAVORITO
        public IActionResult DeleteFavorito(int id)
        {
            this.service.DeleteProductoFavorito(id);
            return RedirectToAction("Favoritos");
        }
    }
}

MvcCacheRedis/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcCacheRedis/Views/Productos/Details.cshtml
@model MvcCacheRedis.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<a asp-controller="Productos" asp-action="SeleccionarFavorito" asp-route-id="@Model.IdProducto">
    <img src="~/images/favorito.png" style="width:40px; height:40px" />
</a>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdProducto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdProducto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            <img src="@Model.Imagen" style="width:150px; height:150px" />
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index" asp-controller="Productos">Back to List</a>
</div>

MvcCacheRedis/Views/Productos/Favoritos.cshtml
@model IEnumerable<MvcCacheRedis.Models.Producto>

@{
    ViewData["Title"] = "Favoritos";
}

<h1>Favoritos</h1>

@if (Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.IdProducto)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Precio)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Imagen)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdProducto)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Precio)
                    </td>
                    <td>
                        <img src="@item.Imagen" style="width: 100px; height: 100px" />
                    </td>
                    <td>
                        <a asp-controller="Productos"
                   asp-action="DeleteFavorito"
                   asp-route-id="@item.IdProducto"
                   class="btn btn-danger">
                            Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1 style="color:blue">
        No hay productos favoritos
    </h1>
}

MvcCacheRedis/Views/Productos/Index.cshtml
@model IEnumerable<MvcCacheRedis.Models.Producto>

@{
    ViewData["Title"] = "Index";
}

<h1>Productos Cache Redis</h1>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>

            <td>
                <a asp-controller="Productos"
                asp-action="Details"
                asp-route-id="@item.IdProducto"
                class="btn btn-info">
                    Details
                </a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcCacheRedis/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcCacheRedis</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcCacheRedis.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcCacheRedis</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Productos" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Productos" asp-action="Favoritos">Productos favoritos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcCacheRedis - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>